### ISSUE TITLE
Question about this repository 

### ISSUE THREAD

**Issue by FoksVHox** [iamkubi/eggs#1]
Are you taking egg requests?

**Comment by iamkubi** [comment]
Sure I'm open to requests.

**Comment by FoksVHox** [comment]
Is it possible that you could create a Farming Simulator 19 egg?

**Comment by iamkubi** [comment]
I've looked at it, but it has to be run with wine so it might be tricky to get working.  Since you need to own a copy of the game to run the dedicated server I haven't really looked at it more.  You need 2 copies of the game and 2 accounts to verify it works.  It's just a pain.

**Comment by FoksVHox** [comment]
I see, well thanks anyhow 🙃
