### ISSUE TITLE
PavlovVR libc++.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by RainOrigami** [iamkubi/eggs#5]
Hi

Thanks for creating an egg for PavlovVR, however I am unable to get the server to start.
This is the log:

```
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/core 
Status: Image is up to date for quay.io/pterodactyl/core:source 
Digest: sha256:3265256f9d729a38cd73f64b2e0545699848a378bee0b15f7c7c6469f07a4d10 
[Pterodactyl Daemon]: Finished pulling Docker container image
:/home/container$ ./PavlovServer.sh -PORT=7777
ln: failed to create hard link '/home/container/.steam/sdk64/steamclient.so': File exists
ln: failed to create hard link '/home/container/Pavlov/Binaries/Linux/steamclient.so': File exists
/home/container/Pavlov/Binaries/Linux/PavlovServer: error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

There seems to be some issue with libc++.so.1, I have tried adding libc++-dev to the apt install command of the install script and reinstalled the server, but this did not solve the issue. I am unsure on how to proceed to fix this issue.

To install this egg I have downloaded the json file and imported it into the Source Engine nest.

Do you know what could cause this issue? Did I make a mistake while installing the egg?

Thank you for your time and work!

**Comment by ZEROPOINTBRUH** [comment]
sounds like an arm64 issue?

**Comment by RainOrigami** [comment]
> sounds like an arm64 issue?

unlikely since the server is running ubuntu 22.04.2 x64

I'm not using this egg, since I have found one that works: https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/pavlov_vr
